### ISSUE TITLE
Driver not working on tft spi 1.8in lcd display 

### ISSUE THREAD

**Issue by anonfaded** [adafruit/Adafruit_CircuitPython_ST7735#20]
There is a s variant of this driver with same name but a s in the end so can you guide on how to make it work? Right now my lcd isn't working and the code runs with no errors, for reference and complete details about my issue please read this: https://github.com/adafruit/circuitpython/issues/9223

**Comment by snkYmkrct** [comment]
You opened an issue in the wrong repo, again. 
todbot gave you the link to the library you are actually using in your code, https://github.com/adafruit/Adafruit_CircuitPython_ST7735R

**Comment by anonfaded** [comment]
oh sorry, i opened issue on the link you provided so i will wait for their reply

**Comment by dhalbert** [comment]
See https://github.com/adafruit/circuitpython/issues/9223#issuecomment-2096268940. Not a library issue.
